apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: core-bank
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'account-service'
        static_configs:
          - targets: ['account-service:8081']
        metrics_path: '/actuator/prometheus'

      - job_name: 'transaction-service'
        static_configs:
          - targets: ['transaction-service:8082']
        metrics_path: '/actuator/prometheus'

      - job_name: 'customer-service'
        static_configs:
          - targets: ['customer-service:8083']
        metrics_path: '/actuator/health'
        scrape_interval: 30s

      - job_name: 'authentication-service'
        static_configs:
          - targets: ['authentication-service:8084']
        metrics_path: '/actuator/health'
        scrape_interval: 30s

      - job_name: 'discovery-service'
        static_configs:
          - targets: ['discovery-service:8761']
        metrics_path: '/actuator/health'
        scrape_interval: 30s
