apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: core-bank-account-service:latest
          imagePullPolicy: Never  # Prevents Kubernetes from trying to pull the image
          ports:
            - containerPort: 8081
          env:
            - name: spring.application.name
              value: "account-service"
            - name: spring.datasource.url
              value: "jdbc:postgresql://postgres:5432/lmwn_db"
            - name: spring.datasource.username
              value: "lmwn_user"
            - name: spring.datasource.password
              value: "12345678"
            - name: eureka.client.service-url.defaultZone
              value: "http://discovery-service:8761/eureka"
            - name: spring.redis.host
              value: "redis"
            - name: spring.redis.port
              value: "6379"
          command: ["java", "-jar", "/app/account-service.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: account-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: account.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 8081