apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: core-bank
  labels:
    app: customer-service
    version: v1
spec:
  replicas: 1  # Scale to 1 replicas for load balancing
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
        version: v1
    spec:
      containers:
      - name: customer-service
        image: customer-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_APPLICATION_NAME
          value: "customer-service"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/lmwn_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "lmwn_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "12345678"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery-service:8761/eureka"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
        # Enable load balancing
        - name: EUREKA_INSTANCE_INSTANCE_ID
          value: "${spring.application.name}:${spring.cloud.client.hostname}:${random.value}"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: SPRING_CLOUD_LOADBALANCER_RIBBON_ENABLED
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: core-bank
  labels:
    app: customer-service
spec:
  type: ClusterIP
  sessionAffinity: None  # Round-robin load balancing
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: customer-service

---
# Horizontal Pod Autoscaler for customer-service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customer-service-hpa
  namespace: core-bank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
