apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: core-bank-discovery-service:latest
          imagePullPolicy: Never  # Prevents Kubernetes from trying to pull the image
          ports:
            - containerPort: 8761
          env:
            - name: spring.application.name
              value: discovery-service
            - name: eureka.client.service-url.defaultZone
              value: "http://discovery-service:8761/eureka"
          command: ["java", "-jar", "/app/discovery-service.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: discovery-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: discovery.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: discovery-service
                port:
                  number: 8761