apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: core-bank
  labels:
    app: authentication-service
    version: v1
spec:
  replicas: 1  # Scale to 1 replica to reduce resource usage
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
        version: v1
    spec:
      containers:
      - name: authentication-service
        image: authentication-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_APPLICATION_NAME
          value: "authentication-service"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/lmwn_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "lmwn_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "12345678"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery-service:8761/eureka"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
        # Disable security for actuator endpoints and expose prometheus
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,prometheus,metrics"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        - name: MANAGEMENT_SECURITY_ENABLED
          value: "false"
        - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
          value: "true"
        # Enable load balancing
        - name: EUREKA_INSTANCE_INSTANCE_ID
          value: "${spring.application.name}:${spring.cloud.client.hostname}:${random.value}"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: SPRING_CLOUD_LOADBALANCER_RIBBON_ENABLED
          value: "false"
        resources:
          requests:
            memory: "128Mi"  # Reduced from 256Mi
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 8084
          initialDelaySeconds: 100
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8084
          initialDelaySeconds: 80
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: core-bank
  labels:
    app: authentication-service
spec:
  type: ClusterIP
  sessionAffinity: None  # Round-robin load balancing
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  selector:
    app: authentication-service

---
# Horizontal Pod Autoscaler for authentication-service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-service-hpa
  namespace: core-bank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
